// Contrato entre app.ts y los módulos de pantalla. Solo tipos.
                                                                                   
                                                         

                        
                         
                
                      
                                                                                               
                 
                                                                          
                                                   
 

                         
                 
                 
                       
                               
                                                                
                       
                              
                                
                                                                            
                           
                                                                                                 
                            
                                                                                               
                            
                        
                                                                                                        
                                                            
                                                                                                         
                            
                                                                                    
                                 
                                                                                                
                                           
                  
                     
                             
                                                                  
                               
 
